# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: run

on:
  schedule:
    # * is a special character in YAML so you have to quote this string
    # - cron: '*/20 * * * *'
  
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 16
        cache: 'yarn'
    - run: rm tzgg.htm
    - run: yarn install
    - run: node main.js
    - name: Commit
      uses: EndBug/add-and-commit@v8
      with:
        message: 'chore: update page'
